### PR TITLE
Add erc20 functions

### PR DESCRIPTION
**Pull request by willKim19**
Adds mint, burn, transfer and batch transfer functions to nightlite. 

Some minor differences from the move from nightfall to nightlite, mostly around moving util functions to other folders.

### CODE REVIEW

**Comment by iAmMichaelConnor** [comment]
@willKim19 I notice a few contract jsons (such as `contracts/FTokenShield.json`) have been added in this PR. If future changes arise to these contracts, how will the json files be updated?

E.g. I'm about to push a change to `FTokenShield.sol` in the Nightfall repo (which removes vkId's and stores vk's in FTokenShield). Would this cause problems for this repo, given that `contracts/FTokenShield.json` is seemingly static in this repo?

**Comment by willKim19** [comment]
Ideally those sorts of changes should be pulled into Nightlite, so all that work would take place in here, so any project using Nightlite always has the correct set of contracts. We'll need to figure out how to tackle this, though I think we should do this after we get the erc20/erc721 functions merged in.

**Comment by lucachaco** [comment]
I also think @iAmMichaelConnor 's changes should be done after we get the erc20/erc721 functions merged in. This way we can at least start experimenting with the mint, burn, transfer and batch transfer functions in tax-wave.

**Comment by iAmMichaelConnor** [comment]
> I also think @iAmMichaelConnor 's changes should be done after we get the erc20/erc721 functions merged in. This way we can at least start experimenting with the mint, burn, transfer and batch transfer functions in tax-wave.

The changes in my Nightlite PR aren't too invasive. And the corresponding changes to Nightfall shouldn't clash too much with the merging of the erc20/721 functions. I'll push the corresponding Nightfall changes as a PR to Nightfall for you to peruse.

**Comment by lucachaco** [comment]
> I also think @iAmMichaelConnor 's changes should be done after we get the erc20/erc721 functions merged in. This way we can at least start experimenting with the mint, burn, transfer and batch transfer functions in tax-wave.

@willKim19 and @iAmMichaelConnor, does it mean we can merge this PR now to use mint, transfer and burn in nightlite?

**Comment by lucachaco** [comment]
> > I also think @iAmMichaelConnor 's changes should be done after we get the erc20/erc721 functions merged in. This way we can at least start experimenting with the mint, burn, transfer and batch transfer functions in tax-wave.
> 
> The changes in my Nightlite PR aren't too invasive. And the corresponding changes to Nightfall shouldn't clash too much with the merging of the erc20/721 functions. I'll push the corresponding Nightfall changes as a PR to Nightfall for you to peruse.
> 
> Edit: Nightfall PR now pushed for you to look at: [EYBlockchain/nightfall#359](https://github.com/EYBlockchain/nightfall/pull/359)
> 
> Both PRs are ready to go - I can't think how they'd interrupt TaxWave work, but if you spot a problem, please (on a private channel) let's discuss.

@willKim19 and @iAmMichaelConnor, does it mean we can merge this PR now to use mint, transfer and burn in nightlite?

**Pull request merged**
